version: "2"

services:

  twl-cvolume:
    container_name: twl-cvolume
    image: busybox
    volumes:
      - .:/app

  twl-webserver-service:
    container_name: twl-webserver-service
    image: bitnami/nginx
    ports:
      - 80:80
    volumes:
      - ./containers-config/site.conf:/bitnami/nginx/conf/vhosts/site.conf
    volumes_from:
      - twl-cvolume

  twl-php-service:
    container_name: twl-php-service
    image: bitnami/php-fpm
    volumes_from:
      - twl-cvolume

  twl-db-service:
    container_name: twl-db-service
    image: bitnami/mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_DATABASE=app
      - MARIADB_USER=app
      - MARIADB_PASSWORD=app
      - MARIADB_ROOT_PASSWORD=app
    volumes:
      - db-volume:/bitnami/mariadb

volumes:
  db-volume:
    driver: local
